### ISSUE TITLE
Disable core dumps

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/docker-qgis-server#148]
# Current behaviour
When QGIS crash this creates a core dump file in /tmp/ which could be very big (160 Mo). If QGIS crash often this will lead to some isse on free disk space.

# Behaviour to implement
Disable core dump file in /tmp (or in option ?)

**Comment by yjacolin** [comment]
This is a first step to avoid issue on free space in our Openshift infrastructure.

**Comment by sbrunner** [comment]
Unrelated to this image
