### ISSUE TITLE
Use /tmp/in empty-dir in openshift

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/docker-qgis-server#149]
# Current behaviour
Temporary files for QGIS (QGIS project file) are opened in /tmp/ which could be full of previous project file.

# Behaviour to implemented
/tmp should be "linked" to an empty-dir config in our openshift infrastructure. Doing so free space will be better managed but we need to move custom script out of this script: https://github.com/camptocamp/docker-qgis-server/blob/3.18/runtime/usr/local/bin/start-server#L11 :
* requirements.txt
* init-env
* pass-env
* profiles (a QGIS files probably)

**Comment by yjacolin** [comment]
Infra team (Mickaël) ask to alert them to test that the empty-dir is correctly created in their openshift infrastructure before to deploy.

**Comment by sbrunner** [comment]
empty-dir is not related to this image
requirements.txt is not in /tmp
init-env and pass-env are not script
profiles is for QGIS
=> Nothing related to this image, Closing
