### ISSUE TITLE
Error while loading shared libraries: libQt5Core.so.5

### ISSUE THREAD

**Issue by mangelofreitas** [camptocamp/docker-qgis-server#166]
I had an error while setting an container working with this image. In Docker for windows with WSL 2 it worked fine, but in an VM with Docker in CentOS i got an error when started the container.

Error output:
```
wms_server | /usr/local/bin/qgis_mapserv.fcgi: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
wms_server |  [warn] [pid 12] mod_fcgid: error reading data from FastCGI server
wms_server |  [error] [pid 12] End of script output before headers: qgis-mapserv-wrapper
```

I thought it was permissions or something, but i got it working by making an Dockerfile where i do this:

```
FROM camptocamp/qgis-server

RUN apt-get update && apt-get install -y \
    binutils \
    && strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

EXPOSE 80
```

And it works, thanks to this comment https://github.com/linuxserver/docker-qbittorrent/issues/103#issuecomment-778796082.

I just wanted to leave it here in the issues in case that someone got the same problem.

**Comment by yjacolin** [comment]
thanks!

@sbrunner may be this is something we can add somewhere? F.A.Q. or a patch ?

**Comment by sbrunner** [comment]
We already have that...
https://github.com/camptocamp/docker-qgis-server/blob/master/Dockerfile#L106

**Comment by yjacolin** [comment]
So I close the issue. Maybe somethin else?! Thanks @sbrunner  and @mangelofreitas

**Comment by felho001** [comment]
Hi i have same issue I now install synology docker with compouse file and error same not started qbittorrent

**Comment by sbrunner** [comment]
Which version do you try to install?

**Comment by felho001** [comment]
I don't know, my compouse file try too install latest version 
"qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent"
